### PR TITLE
[llbuild3] Cleanup and Implement action cache support

### PR DESCRIPTION
**Pull request by dmbryson**
- Adds InMemoryActionCache
- Expands CAS structures and adds InMemoryCASDatabase
- Caches task transitions, though request replay is unimplemented
- Cleans up the framework name
- Adds vendored thirdparty BLAKE3 portable C implementation
- Fixes up LICENSE.txt to properly reference thirdparty code
- Removes unused thirdparty code

### CODE REVIEW

**Comment by jakepetroules** [comment]
@swift-ci please smoke test windows

**Review by jakepetroules — APPROVED** [review]

**Comment by dmbryson** [comment]
@swift-ci please smoke test windows

**Comment by dmbryson** [comment]
@swift-ci please test windows

**Comment by dmbryson** [comment]
@swift-ci please smoke test windows

**Pull request merged**
