### PR TITLE
Delete CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by parispittman**
no longer using this contributing template

### CODE REVIEW

**Review by dmbryson — APPROVED** [review]

**Comment by dmbryson** [comment]
@swift-ci please smoke test

**Comment by jakepetroules** [comment]
@swift-ci please smoke test

**Comment by owenv** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test

**Comment by shahmishal** [comment]
@swift-ci please smoke test Windows

**Pull request merged**
