### PR TITLE
Update swift-toolchain-sqlite

### PR DESCRIPTION
**Pull request by jakepetroules**
Adapt to rename RE swiftlang/swift-toolchain-sqlite#5

### CODE REVIEW

**Review by owenv — APPROVED** [review]

**Review by mirza-garibovic — APPROVED** [review]

**Comment by jakepetroules** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7909
@swift-ci please test

**Comment by jakepetroules** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7909
@swift-ci please smoke test macOS Linux

**Comment by jakepetroules** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7909
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7909
@swift-ci please smoke test Linux

**Review by dmbryson — APPROVED** [review]

**Comment by jakepetroules** [comment]
swiftlang/swift-package-manager#7909
@swift-ci please test

**Comment by dmbryson** [comment]
https://github.com/swiftlang/swift-package-manager/pull/7909
@swift-ci please smoke test Linux

**Comment by jakepetroules** [comment]
swiftlang/swift-package-manager#7909
swiftlang/swift-toolchain-sqlite#7
@swift-ci please test

**Comment by jakepetroules** [comment]
swiftlang/swift-package-manager#7909
swiftlang/swift-toolchain-sqlite#7
@swift-ci please smoke test macOS

**Comment by jakepetroules** [comment]
swiftlang/swift-package-manager#7909
swiftlang/swift-toolchain-sqlite#7
@swift-ci please smoke test Linux

**Comment by jakepetroules** [comment]
swiftlang/swift-package-manager#7909
swiftlang/swift-toolchain-sqlite#7
@swift-ci please test Windows

**Pull request merged**
